{% set name = "pheasant" %}
{% set version = "2.5.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c648330166ffabaf7f93017cbca98be016abbea493ea9fb69468b1ba0f7df284

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pheasant = pheasant.main:cli

requirements:
  host:
    - python >3.7
    - pip
    - setuptools
  run:
    - python >3.7
    - click
    - ipykernel
    - markdown
    - jinja2
    - termcolor
    - colorama
    - pyyaml

test:
  imports:
    - pheasant
  commands:
    - pheasant list

about:
  home: https://github.com/daizutabi/pheasant
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Documentation tool for Markdown conversion by Jupyter client
  doc_url: https://pheasant.daizutabi.net/
  dev_url: https://github.com/daizutabi/pheasant

extra:
  recipe-maintainers:
    - daizutabi
    - pkestene
